################################################################################
# Grid Option
################################################################################
gridOption.shrinkToFit=false
gridOption.rowNumbers=true
gridOption.sortable=true
gridOption.panelVisible=false
gridOption.enterToNextRow=true
gridOption.acceptZero=false
gridOption.multiSelect=true
gridOption.singleSelect=false

################################################################################
# JEUS Server Log Paths
################################################################################
# Operator Server Log Paths (JEUS 7 -> JEUS 8 업그레이드 시 경로 수정 필요)
eversrm.log.path.op.epop11=/logs/tmax/jeus7/epop11/JeusServer.log
eversrm.log.path.op.epop21=/logs/tmax/jeus7/epop21/JeusServer.log
eversrm.log.path.op.epcs11=/logs/tmax/jeus7/epcs11/JeusServer.log
eversrm.log.path.op.epcs21=/logs/tmax/jeus7/epcs21/JeusServer.log