################################################################################
# Grid Option
################################################################################
gridOption.shrinkToFit=false
gridOption.rowNumbers=true
gridOption.sortable=true
gridOption.panelVisible=false
gridOption.enterToNextRow=true
gridOption.acceptZero=false
gridOption.multiSelect=true
gridOption.singleSelect=false

################################################################################
# JEUS Server Log Paths
################################################################################
# Front Server Log Path (JEUS 7 -> JEUS 8 업그레이드 시 경로 수정 필요)
eversrm.log.path.front=/logs/tmax/jeus7/epcs11/JeusServer.log