
id=z120811300200
pass=SGIC
#id=A111111111900
#pass=TEST

recv_path=/svc/nhepro/NHeProFront/SGIxLinker/data/recv/

main_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/

temp_path=/svc/nhepro/NHeProFront/SGIxLinker/templates/

log_path=/svc/nhepro/NHeProFront/SGIxLinker/logs/

secu_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/secu.cfg

self_cert_number=1

kmcert=/svc/nhepro/NHeProFront/SGIxLinker/cert/sgic/kmCert.der

isInfoLog=true
isErrorLog=true
isDebugLog=true