
#id=z120811300200 // 서울보증보험 아이디로 수정
#pass=SGIC
#id=A111111111900
#pass=TEST
id=A120870175500
pass=A120870175500

recv_path=S:/client_project/NH_SGIxLinker/WebContent/data/recv/

main_path=S:/client_project/NH_SGIxLinker/WebContent/conf/

temp_path=S:/client_project/NH_SGIxLinker/WebContent/templates/

log_path=S:/client_project/NH_SGIxLinker/WebContent/logs/

secu_path=S:/client_project/NH_SGIxLinker/WebContent/conf/secu.cfg

self_cert_number=1

#sender -> sgic로 수정 후 테스트
kmcert=S:/client_project/NH_SGIxLinker/WebContent/cert/sender/kmCert.der

isInfoLog=true
isErrorLog=true
isDebugLog=true