######################################################
#
#  id               : 송신자 ID 리스트
#  pass             : 송신자 패스워드 리스트
#  recv_path        : 수신 문서 경로
#  main_path        : 환경설정 파일 경로
#  temp_path        : templetes 경로
#  log_path         : log파일 경로
#  secu_path        : 보안 설정 파일
#  self_cert_number : 전자서명 검증 시 사용할 인증서 선택
#  kmcert           : 상대방 암호화 공개키
#  isInfoLog        : info레벨로그 출력여부
#  isErrorLog       : error레벨로그 출력여부
#  isDebugLog       : debug레벨로그 출력여부
#
######################################################

id=z120811300200
pass=SGIC
#id=A111111111900
#pass=TEST

#수신문서 경로
recv_path=/svc/nhepro/NHeProFront/SGIxLinker/data/recv/

#환경설정 파일 경로
main_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/

#templets 경로
temp_path=/svc/nhepro/NHeProFront/SGIxLinker/templates/

#log파일 경로
log_path=/svc/nhepro/NHeProFront/SGIxLinker/logs/

#secu.cfg 경로
secu_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/secu.cfg

#전자서명 검증 시 사용할 인증서
self_cert_number=1

#상대방 암호화 공개키
kmcert=/svc/nhepro/NHeProFront/SGIxLinker/cert/sender/kmCert.der

isInfoLog=true
isErrorLog=true
isDebugLog=true
