url=http://localhost:8080/NH_SGIxLinker/samples/recv.jsp
#url=http://egisu-t.sgic.co.kr/servlets/SgicAPI/SgicRecvAPIUTF8

kmcert=S:/client_project/NH_SGIxLinker/WebContent/cert/sender/kmCert.der

id=A120870175500
pass=A120870175500
#id=A111111111900
#pass=TEST

decDir=S:/client_project/NH_SGIxLinker/WebContent/data/
outDir=S:/client_project/NH_SGIxLinker/WebContent/data/
recv_path=S:/client_project/NH_SGIxLinker/WebContent/data/recv/
main_path=S:/client_project/NH_SGIxLinker/WebContent/conf/
temp_path=S:/client_project/NH_SGIxLinker/WebContent/templates/
log_path=S:/client_project/NH_SGIxLinker/WebContent/logs/
secu_path=S:/client_project/NH_SGIxLinker/WebContent/conf/secu.cfg
self_cert_number=1
cid_list=cid:ebxmlpayload00@sgic.co.kr

# http://www.w3.org/2000/09/xmldsig#sha1
# http://www.w3.org/2001/04/xmlenc#sha256

hashAlgo=http://www.w3.org/2000/09/xmldsig#sha1

isInfoLog=true
isErrorLog=true
isDebugLog=true

#SSL or TLS (Default: SSL)
sslType=SSL