######################################################
#
#  url              : 상대방 서버 URL(서울보증보험)
#  kmcert           : 상대방 암호화 공개키(서울보증보험)
#  id               : 송신자 ID 리스트
#  pass             : 송신자 패스워드 리스트
#  decDir           : 전문xml이 암호화되기전 mime파일 경로
#  outDir           : 전문xml이 암호화 후 mime파일 경로
#  main_path        : 환경설정 파일 경로
#  temp_path        : templates 경로
#  log_path         : log파일 경로
#  secu_path        : 보안 설정 파일
#  self_cert_number : 전자서명 생성 시 사용할 인증서 선택
#  cid_list         : cid
#  isInfoLog        : info레벨로그 출력여부
#  isErrorLog       : error레벨로그 출력여부
#  isDebugLog       : debug레벨로그 출력여부
#  signAlgo         : XML 서명 알고리즘 식별자
#  hashAlgo         : XML 해쉬 알고리즘 식별자
#
#######################################################
#url=http://egis.sgic.co.kr/servlets/SgicAPI/SgicRecvAPI
#url=http://222.99.15.33/servlets/SgicAPI/SgicRecvAPI
#url=http://127.0.0.1:8380/SGIxLinker/samples/recv.jsp
#url=http://test.first-epro.com/SGIxLinker/samples/recv.jsp
############ \uAC1C\uBC1C EUC-KR #############
#url=http://egis-t.sgic.co.kr/servlets/SgicAPI/SgicRecvAPI
############ \uAC1C\uBC1C UTF-8 #############
url=http://egisu-t.sgic.co.kr/servlets/SgicAPI/SgicRecvAPIUTF8
#url=http://localhost:8380/SGIxLinker/samples/recv.jsp
############ \uC6B4\uC601 EUC-KR #############
#url=http://egis.sgic.co.kr/servlets/SgicAPI/SgicRecvAPI
############ \uC6B4\uC601 UTF-8 #############
#url=http://egisu.sgic.co.kr/servlets/SgicAPI/SgicRecvAPIUTF8

#kmcert=/svc/nhepro/NHeProFront/SGIxLinker/cert/sender/kmCert.der
kmcert=/svc/nhepro/NHeProFront/SGIxLinker/cert/sgic/kmCert.der

id=A120870175500
pass=A120870175500
#id=A119810231600
#pass=HYUNDAIHYUNDAI

decDir=/svc/nhepro/NHeProFront/SGIxLinker/data/
outDir=/svc/nhepro/NHeProFront/SGIxLinker/data/
recv_path=/svc/nhepro/NHeProFront/SGIxLinker/data/recv/
main_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/
temp_path=/svc/nhepro/NHeProFront/SGIxLinker/templates/
log_path=/logs/nhepro/SGIxLinker/
secu_path=/svc/nhepro/NHeProFront/SGIxLinker/conf/secu.cfg
self_cert_number=1
cid_list=cid:ebxmlpayload00@sgic.co.kr

# http://www.w3.org/2000/09/xmldsig#sha1
# http://www.w3.org/2001/04/xmlenc#sha256

hashAlgo=http://www.w3.org/2000/09/xmldsig#sha1

isInfoLog=true
isErrorLog=true
isDebugLog=true
