defaultGateCd=100
defaultLangCd=KO

systemDateTime=SYSDATE
gridDateFormat='yyyyMMdd'

toStringFS=, 'yyyyMMdd')
toStringFS2=, 'YYYY-MM-DD')
toStringFM=, 'YYYY-MM-DD HH24:MI')
toStringFL=, 'YYYY-MM-DD HH24:MI:SS')

toChar=TO_CHAR
toCharFS=TO_CHAR(
toCharFS2=TO_CHAR(
toCharFM=TO_CHAR(
toCharFL=TO_CHAR(

dateToString=TO_CHAR(SYSDATE, 'YYYYMMDD')
timeToString=TO_CHAR(SYSDATE, 'HH24MISS')
dateTimeToString=TO_CHAR(SYSDATE, 'YYYYMMDD HH24MISS')

dateParamS=TO_DATE( 
dateParamEF=||'000000', 'YYYYMMDD HH24:MI:SS') 
dateParamET=||'235959', 'YYYYMMDD HH24:MI:SS')

stringToDateStart=TO_DATE(
stringToDateEnd=, 'YYYYMMDD HH24:MI:SS') 

dbo=
dboEnd=
functionStart=
functionEnd=
fromDual=FROM DUAL

toNumber=notYetImplement
stringMerge=||
mergeInto=INTO
mergeAs=

#system function
nvl=NVL
length=LENGTH
substr=SUBSTR
lpad=LPAD
rpad=RPAD
trunc=TRUNC
trim=TRIM
nolock=

### lpad ~trim \uAE4C\uC9C0 \uAE30\uC874 \uB300\uB85C \uC4F0\uC2DC\uACE0 \uD391\uC158 \uB9C8\uC9C0\uB9C9\uC5D0 dboEnd\uB97C \uC4F0\uC154\uC11C \uAD04\uD638\uAC00 \uB2EB\uD788\uB3C4\uB85D \uD574\uC8FC\uC138\uC694.

xx1Enc=
xx1Dec=

### S : \uC8FC\uBBFC\uBC88\uD638, D : \uACC4\uC88C\uBC88\uD638, N : \uC774\uB984
### P : \uC804\uD654/\uD578\uB4DC\uD3F0, M : Email, A : \uC8FC\uC18C, P : \uBE44\uBC00\uBC88\uD638
xx1EndS=
xx1EndD=
xx1EndN=
xx1EndP=
xx1EndM=
xx1EndA=
xx1EndW=

### LIKE \uD544\uB4DC
xx1EncL=
### LIKE \uD30C\uB77C\uBA54\uD0C0
xx1EncLs=

### S : \uC8FC\uBBFC\uBC88\uD638, D : \uACC4\uC88C\uBC88\uD638, N : \uC774\uB984
### P : \uC804\uD654/\uD578\uB4DC\uD3F0, M : Email, A : \uC8FC\uC18C, P : \uBE44\uBC00\uBC88\uD638
xx1EndLS=
xx1EndLD=
xx1EndLN=
xx1EndLP=
xx1EndLM=
xx1EndLA=
xx1EndLW=