#defaultGateCd='100'
#defaultLangCd='KO'

#systemDateTime=getdate()
#gridDateFormat='yyyyMMdd'

#toStringFS=, 112)
#toStringFS2=, 23)
#toStringFM=, 120)
#toStringFL=, 120)

#toChar=FORMAT \uC548\uC500
#toCharFS=CONVERT(CHAR(8),
#toCharFS2=CONVERT(CHAR(10),
#toCharFM=CONVERT(CHAR(16),
#toCharFL=CONVERT(CHAR(19),

#dateToString=CONVERT(NVARCHAR, GETDATE(),112)
#timeToString=REPLACE(CONVERT(NVARCHAR, GETDATE(), 24), ':', '') \uC548\uC500.
#dateTimeToString=CONVERT(NVARCHAR, GETDATE(),112) + REPLACE(CONVERT(NVARCHAR, GETDATE(), 24), ':', '') \uC548\uC500

#dateParamS=CONVERT(DATETIME,
#dateParamEF= + ' 00:00:00')
#dateParamET= + ' 23:59:59')

#stringToDateStart=
#stringToDateEnd=

#dbo=dbo.
#dbo=dbo.
#dboEnd=
#functionStart=(SELECT * FROM dbo.
#functionEnd=)
#fromDual=

#toNumber=notYetImplement \uC548\uC500.
#stringMerge=+  --> /*+*/+ \uBCC0\uACBD \uC55E\uC73C\uB85C\uB294 /*+*/|| /*+*/+ \uC774\uB7F0\uC2DD\uC73C\uB85C \uC4F0\uC790
#mergeInto= INTO \uB85C \uBCC0\uACBD \uC774\uC0C1\uC5C6\uC74C.
#mergeAs=AS

#####system function
#nvl=ISNULL
#length=LEN --> dbo.SF_LENGTH
#substr=SUBSTRING --> dbo.SF_SUBSTR
#lpad=dbo.fn_lpad
#rpad=dbo.fn_rpad \uC548\uC500.
#trunc=dbo.fn_trunc \uC548\uC500.
#trim=dbo.fn_trim --> dbo.SF_TRIM
#nolock=with (NOLOCK)
#rowlock=with (ROWLOCK)

### lpad ~trim \uAE4C\uC9C0 \uAE30\uC874 \uB300\uB85C \uC4F0\uC2DC\uACE0 \uD391\uC158 \uB9C8\uC9C0\uB9C9\uC5D0 dboEnd\uB97C \uC4F0\uC154\uC11C \uAD04\uD638\uAC00 \uB2EB\uD788\uB3C4\uB85D \uD574\uC8FC\uC138\uC694.

#xx1Enc= \uC548\uC500
#xx1Dec=

### S : \uC8FC\uBBFC\uBC88\uD638, D : \uACC4\uC88C\uBC88\uD638, N : \uC774\uB984
### P : \uC804\uD654/\uD578\uB4DC\uD3F0, M : Email, A : \uC8FC\uC18C, P : \uBE44\uBC00\uBC88\uD638
#xx1EndS= \uC548\uC500
#xx1EndD= \uC548\uC500
#xx1EndN=
#xx1EndP=
#xx1EndM=
#xx1EndA=
#xx1EndW=

### LIKE \uD544\uB4DC
#xx1EncL=
### LIKE \uD30C\uB77C\uBA54\uD0C0
#xx1EncLs=

### S : \uC8FC\uBBFC\uBC88\uD638, D : \uACC4\uC88C\uBC88\uD638, N : \uC774\uB984
### P : \uC804\uD654/\uD578\uB4DC\uD3F0, M : Email, A : \uC8FC\uC18C, P : \uBE44\uBC00\uBC88\uD638
#xx1EndLS= \uC548\uC500
#xx1EndLD= \uC548\uC500
#xx1EndLN=
#xx1EndLP=\uC548\uC500
#xx1EndLM=\uC548\uC500
#xx1EndLA=\uC548\uC500
#xx1EndLW=\uC548\uC500