#########################################################
evf.debug.mode=true

#########################################################
# azure, myHome, deepBlue, neo
evf.theme=neo2

#########################################################
evf.common.include.JspFilePath=/include/commonInclude.jsp
evf.common.include.JavascriptFilePath=
evf.common.include.CssFilePath=
evf.config.ui.select.defaultPlaceHolder=\uC804\uCCB4

evf.filter.encoding=UTF-8